# Generated by Django 6.0.3 on 2026-04-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_remove_student_course_remove_student_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='year_of_study',
            field=models.IntegerField(),
        ),
    ]
