# Generated by Django 6.0.4 on 2026-05-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_role_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('report', 'Report Viewer')], default='student', max_length=20),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
