# Generated by Django 6.0.3 on 2026-05-02 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_full_name_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('grade', models.CharField(choices=[('A+', 'Outstanding (A+)'), ('A', 'Excellent (A)'), ('B', 'Good (B)'), ('C', 'Average (C)'), ('D', 'Below Average (D)'), ('F', 'Fail (F)')], default='F', max_length=3)),
                ('is_passed', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_report', to='core.enrollment')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
